[package]
name = "virtio"
version = "0.1.0"
edition = "2021"

[features]
mock = ["dep:mockall"]

[dependencies]
vm-memory = { version = "0.16.1", features = ["backend-mmap", "backend-atomic"] }
virtio-queue = { version = "0.14.0" }
anyhow = "1.0.95"
event_manager = {path = "../event_manager"} # only required for EventSource which should be moved to other crate?
vmm-sys-util = "0.12.1"
mockall = { version = "0.13.1", optional = true }

