[package]
name = "vhost-user"
version = "0.14.0"
authors = ["The Cloud Hypervisor Authors"]
keywords = ["vhost-user", "virtio"]
description = "A framework to build vhost-user backend service daemon"
repository = "https://github.com/rust-vmm/vhost"
edition = "2021"
license = "Apache-2.0"

[features]
postcopy = ["vhost/postcopy", "userfaultfd"]

[dependencies]
libc = "0.2.39"
log = "0.4.17"
userfaultfd = { version = "0.8.1", optional = true }
vhost = { version = "0.13.0", features = ["vhost-user-backend"] }
virtio = { path = "../virtio" }
virtio-bindings = "0.2.5"
virtio-queue = "0.14.0"
vm-memory = { version = "0.16.1", features = ["backend-mmap", "backend-atomic", "backend-bitmap"] }
vmm-sys-util = "0.12.1"
event_manager = { path = "../event_manager" }
smallvec = "2.0.0-alpha.10"
arc-swap = "1.7.1"
anyhow = "1.0.95"

[dev-dependencies]
nix = { version = "0.29", features = ["fs"] }
uuid = { version = "1.8.0", features = ["v4"] }
vhost = { version = "0.13.0", features = ["test-utils"] }
vm-memory = { version = "0.16.1", features = ["backend-mmap", "backend-atomic"] }
tempfile = "3.2.0"
